services:
    movies:
        build:
            context: .
            dockerfile: compose/dev/Dockerfile
        
        env_file:
            - .envs/dev/.env

        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app/
        ports:
            - 8000:8000

        depends_on:
            - movies-db
    movies-db:
        image: postgres:16
        volumes:
            - postgres_data:/var/lib/postgresql/data/

        env_file:
            - .envs/dev/.env
        # environment:
        #     - "POSTGRES_HOST_AUTH_METHOD=trust"
        #     - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
        #     - DATABASE_URL=${DATABASE_URL}

volumes:
  postgres_data: